#spring:
#  datasource:
#   url: jdbc:h2:mem:testdb
#   username: testdb
#   password: 123456
# h2:
#   console:
#     enabled: true
#     path: /h2-console
#     settings:
#       trace: false
#       web-allow-others: false
# jpa:
#   open-in-view: false
#   hibernate:
#     ddl-auto: update
#   show-sql: true
#   properties:
#     hibernate:
#       format_sql: true
